version: "3.4"
services:
  # moove-node:
  #   build: .
  #   container_name: moove-node
  #   restart: always
  #   ports:
  #     - 5377:3007
  #   depends_on:
  #     - moove-mongo
  #     - moove-redis
  #     - moove-zookeeper
  #     - moove-kafka
  #   environment:
  #     - CONTAINER_SERVICE=Docker
  #     - NODE_ENV=production
  moove-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    container_name: moove-mongo
    restart: always
  moove-redis:
    image: redis
    ports:
      - 6379:6379
    container_name: moove-redis
    restart: always
  moove-zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    container_name: moove-zookeeper
    volumes:
      - "zookeeper_data:/data/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  moove-kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    container_name: moove-kafka
    volumes:
      - "kafka_data:/data/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=moove-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - moove-zookeeper

volumes:
  mongo_data:
  zookeeper_data:
  kafka_data:
